parsers:
  javascript:
    enable_partials: yes

coverage:
  status:
    patch:
      default:
        target: auto
        base: auto
        threshold: 1%
        flags:
          - unit
          - integration
        paths:
          - lib
          - backend
        only_pulls: true

ignore:
  - "*.js"
